### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
You use DBAPI (while say PostgreSQL package uses DBI.jl protocol).

I think that is the future, and do wander if any abstraction currently works for all databases? I know JDBC isn't needed for PostgreSQL, but you could use.., but it seems if I go with DBI I would be stuck..

[I saw some other typo and can't find again.. maybe it wasn't actually in this package or file..]

**Comment by PallHaraldsson** [comment]
I see not "DBAPI" (but not really..): https://github.com/JuliaDB/PostgreSQL.jl/pull/43

Any idea why Julia 0.5 tests are failing? Is it because of v0.0.3-tag that is for Julia 0.3? Just learning.. maybe there needs to be a tag for Julia 0.4+

**Comment by aviks** [comment]
The tests are failing on 0.5 since it needs master of JavaCall. A new 0.5 compatible version of JavaCall needs to be tagged.

**Comment by PallHaraldsson** [comment]
I'm still learning (as you could see here https://github.com/JuliaInterop/pyjulia/pull/56 ) but it seems the red cross at DataFrame[s] was no problem.. so my other doc-changes also mergeble already(?).

**Comment by PallHaraldsson** [comment]
I did mean for the link to be implicit: `[DataFrames](https://github.com/JuliaStats/DataFrames.jl)`

Not sure how to fix..

**Comment by PallHaraldsson** [comment]
`[DataFrames]`(https://github.com/JuliaStats/DataFrames.jl)

**Pull request merged**
